spring:
  application:
    name: licensingservice
  profiles:
    active:
      default
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: "optional:configserver:"

server:
  port: 6000