spring:
  application:
    name: organizationservice
  profiles:
    active:
      default
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: "optional:configserver:"

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

        